name: Build and test changes

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./EShop.sln

      - name: Build
        run: dotnet build ./EShop.sln --configuration release --no-restore

      - name: Publish
        run: dotnet publish ./EShop.sln --configuration release
