name: Build and test changes

on: push

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./EShop.sln

      - name: Build
        run: dotnet build ./EShop.sln --configuration release --no-restore

      - name: Unit tests
        run: dotnet test ./EShop.sln

  front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.x'

      # - name: Dependencies
      #   run: npm ci ./src/ClientApp

      - name: Build
        run: npm run build ./ClientApp